export const tokens = {
  colors: {
    bgPrimary: "var(--color-bg-primary)",
    bgSecondary: "var(--color-bg-secondary)",
    bgCard: "var(--color-bg-card)",
    bgNode: "var(--color-bg-node)",
    textPrimary: "var(--color-text-primary)",
    textSecondary: "var(--color-text-secondary)",
    textMuted: "var(--color-text-muted)",
    accentPrimary: "var(--color-accent-primary)",
    accentSuccess: "var(--color-accent-success)",
    accentWarning: "var(--color-accent-warning)",
    accentError: "var(--color-accent-error)",
    borderPrimary: "var(--color-border-primary)",
    borderAccent: "var(--color-border-accent)",
  },
  spacing: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    xxl: "3rem",
  },
  radius: {
    sm: "0.375rem",
    md: "0.75rem",
    lg: "1.25rem",
    xl: "1.75rem",
    full: "9999px",
  },
  font: {
    sm: "clamp(0.75rem, 1.5vw, 0.875rem)",
    md: "clamp(0.875rem, 2vw, 1rem)",
    lg: "clamp(1rem, 2.5vw, 1.25rem)",
    xl: "clamp(1.25rem, 3vw, 1.75rem)",
    xxl: "clamp(1.75rem, 4vw, 2.5rem)",
    hero: "clamp(2rem, 5vw, 3.5rem)",
  },
  transition: {
    fast: "150ms ease-out",
    base: "250ms ease-out",
    slow: "400ms ease-out",
  },
} as const;